Issue #79 animator view
aamks/aamks pull request #156
Opened 2023-10-29 12:58 UTC by mmackiewicz97

Create a new look of single simulation page, added sorting to animations table

2023-11-01 18:28 UTC, AleksanderKamienski requested changes

2023-11-02 07:19 UTC, kowalskiw commented on gui/animator/anim.php
> +	<th>WRI</th>
Thank you, the key should be "societal" - my bad.

2023-11-02 08:54 UTC, kowalskiw commented on gui/animator/anim.php
> +	<th>WRI</th>
Fixed in https://github.com/aamks/aamks/pull/156/commits/04a47d256105881a3bb261379d8e4374fdcd99c7

2023-11-02 08:55 UTC, kowalskiw approved these changes
Works fine, to bo developed and improved in the future.

2023-11-02 11:11 UTC, AleksanderKamienski approved these changes

2023-11-02 11:26 UTC, kowalskiw commented
Separate button for plotting in the background to be considered before merge.

2023-11-02 17:34 UTC, merged