TrianglesBVH class added to improve navmesh
aamks/aamks pull request #168
Opened 2023-11-06 09:48 UTC by AleksanderKamienski

2023-11-06 11:35 UTC, mmackiewicz97 requested changes

2023-11-06 11:35 UTC, mmackiewicz97 commented on installer/sql.sql
>      results text
before i_risk there should be a comma

2023-11-09 07:43 UTC, kowalskiw approved these changes

2023-11-09 09:12 UTC, mmackiewicz97 approved these changes

2023-11-09 09:13 UTC, merged